---
- hosts: localhost
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: cron, tags: ['cron'] }
    - { role: microcode, tags: ['microcode'], when: "'GenuineIntel' in ansible_processor" }
    - { role: ssh, tags: ['ssh'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: ssd, tags: ['ssd'] }
    - { role: nettools, tags: ['nettools'] }
    - { role: ntp, tags: ['ntp'] }
    - { role: editors, tags: ['editors'] }
    - { role: filesystems, tags: ['filesystems'] }
    - { role: archive, tags: ['archive'] }
    - { role: udisks, tags: ['udisks'] }
    - { role: rtorrent, tags: ['rtorrent'] }
    - { role: hashicorp, tags: ['hashicorp'] }
    - { role: virtualenv, tags: ['virtualenv'] }
    - { role: borg, tags: ['borg'] }
    - { role: postgresql, tags: ['postgresql'] }
    - { role: aws, tags: ['aws'] }
    - { role: wormhole, tags: ['wormhole'] }
    - { role: dropbox, tags: ['dropbox'] }
    - { role: docker, tags: ['docker'] }
    - { role: python, tags: ['python']}
    - { role: mongodb, tags: ['mongodb'] }
    - { role: haskell, tags: ['haskell'] }
    - { role: plex, tags: ['plex'] }
    - { role: samba, tags: ['samba'] }
    vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"
