---
- hosts: localhost
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: cron, tags: ['cron'] }
    - { role: microcode, tags: ['microcode'], when: "'GenuineIntel' in ansible_processor" }
    #- { role: grsec, tags: ['grsec'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: ssd, tags: ['ssd'] }
    #- { role: iptables, tags: ['iptables'] }
    - { role: nettools, tags: ['nettools'] }
    - { role: ntp, tags: ['ntp'] }
    #- { role: tor, tags: ['tor'], when: "tor is defined" }
    #- { role: unbound, tags: ['unbound'] }
    - { role: editors, tags: ['editors'] }
    - { role: filesystems, tags: ['filesystems'] }
    - { role: archive, tags: ['archive'] }
    - { role: udisks, tags: ['udisks'] }
    #- { role: bitlbee, tags: ['bitlbee'] }
    #- { role: git-annex, tags: ['git-annex'], when: "gitannex is defined" }
    - { role: rtorrent, tags: ['rtorrent'] }
    #- { role: virtualbox, tags: ['virtualbox'] }
    - { role: hashicorp, tags: ['hashicorp'] }
    - { role: virtualenv, tags: ['virtualenv'] }
    #- { role: cryptshot, tags: ['cryptshot'], when: "cryptshot is defined" }
    - { role: borg, tags: ['borg'] }
    #- { role: tarsnap, tags: ['tarsnap'] }
    - { role: postgresql, tags: ['postgresql'] }
    - { role: aws, tags: ['aws'] }
    #- { role: parcimonie, tags: ['parcimonie'], when: "tor is defined" }
    #- { role: localtime, tags: ['localtime'], when: "localtime is defined"  }
    - { role: wormhole, tags: ['wormhole'] }
    - { role: dropbox, tags: ['dropbox'] }
    - { role: docker, tags: ['docker'] }
    - { role: python, tags: ['python']}
    - { role: mongodb, tags: ['mongodb'] }
    - { role: haskell, tags: ['haskell'] }
    - { role: plex, tags: ['plex'] }
    - { role: samba, tags: ['samba'] }
    vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"
