---
- name: Install Runc
  pacman: name=runc state=present
  tags:
    - docker

- name: Install Containerd
  pacman: name=containerd state=present
  tags:
    - docker

- name: Install Docker
  pacman: name=docker state=present
  tags:
    - docker

- name: Enable Docker service
  service: name=docker.service enabled=no
  tags:
    - docker

- name: Add user to the docker group
  user: name={{ user.name }} groups=docker append=yes
  tags:
    - docker
