---
- name: Install Bash
  pacman: name={{ item }} state=present
  with_items:
    - bash
    - bash-completion
  tags:
    - shell

- name: Install ZSH
  pacman: name={{ item }} state=present
  with_items:
    - zsh
    - zsh-completions
  tags:
    - shell

- name: Install starship
  pacman:
    name:
      - starship
    state: present
  tags:
    - shell

- name: Install shell helpers
  aur:
    name:
      - shell-color-scripts
      - antibody
    user: "{{user.name}}"
  tags:
    - aur
    - shell

- name: Install fish
  pacman:
    name: fish
    state: present
  tags:
    - shell
